# Form implementation generated from reading ui file 'confirm_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.dialog_label = QtWidgets.QLabel(Dialog)
        self.dialog_label.setGeometry(QtCore.QRect(120, 30, 241, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dialog_label.setFont(font)
        self.dialog_label.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignTop)
        self.dialog_label.setObjectName("dialog_label")
        self.dialog_button = QtWidgets.QPushButton(Dialog)
        self.dialog_button.setGeometry(QtCore.QRect(240, 220, 113, 32))
        self.dialog_button.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.dialog_button.setObjectName("dialog_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dialog_label.setText(_translate("Dialog", "TextLabel"))
        self.dialog_button.setText(_translate("Dialog", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
