# Form implementation generated from reading ui file 'error_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_error_dialog(object):
    def setupUi(self, error_dialog):
        error_dialog.setObjectName("error_dialog")
        error_dialog.resize(320, 240)
        self.error_dialog_button = QtWidgets.QPushButton(error_dialog)
        self.error_dialog_button.setGeometry(QtCore.QRect(170, 180, 113, 32))
        self.error_dialog_button.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.error_dialog_button.setObjectName("error_dialog_button")
        self.error_dialog_label = QtWidgets.QLabel(error_dialog)
        self.error_dialog_label.setGeometry(QtCore.QRect(90, 50, 201, 101))
        self.error_dialog_label.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignTop)
        self.error_dialog_label.setObjectName("error_dialog_label")

        self.retranslateUi(error_dialog)
        QtCore.QMetaObject.connectSlotsByName(error_dialog)

    def retranslateUi(self, error_dialog):
        _translate = QtCore.QCoreApplication.translate
        error_dialog.setWindowTitle(_translate("error_dialog", "Form"))
        self.error_dialog_button.setText(_translate("error_dialog", "Ok"))
        self.error_dialog_label.setText(_translate("error_dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error_dialog = QtWidgets.QWidget()
    ui = Ui_error_dialog()
    ui.setupUi(error_dialog)
    error_dialog.show()
    sys.exit(app.exec())
