# Form implementation generated from reading ui file 'pass_ui.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 214)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.img_label = QtWidgets.QLabel(self.main_widget)
        self.img_label.setGeometry(QtCore.QRect(0, -10, 201, 191))
        self.img_label.setMinimumSize(QtCore.QSize(201, 191))
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap("logo.png"))
        self.img_label.setObjectName("img_label")
        self.website_edit = QtWidgets.QLineEdit(self.main_widget)
        self.website_edit.setGeometry(QtCore.QRect(380, 20, 251, 21))
        self.website_edit.setObjectName("website_edit")
        self.email_edit = QtWidgets.QLineEdit(self.main_widget)
        self.email_edit.setGeometry(QtCore.QRect(380, 50, 251, 21))
        self.email_edit.setObjectName("email_edit")
        self.password_edit = QtWidgets.QLineEdit(self.main_widget)
        self.password_edit.setGeometry(QtCore.QRect(380, 80, 251, 21))
        self.password_edit.setObjectName("password_edit")
        self.website_label = QtWidgets.QLabel(self.main_widget)
        self.website_label.setGeometry(QtCore.QRect(220, 20, 151, 21))
        self.website_label.setObjectName("website_label")
        self.email_label = QtWidgets.QLabel(self.main_widget)
        self.email_label.setGeometry(QtCore.QRect(220, 50, 151, 21))
        self.email_label.setObjectName("email_label")
        self.password_label = QtWidgets.QLabel(self.main_widget)
        self.password_label.setGeometry(QtCore.QRect(220, 80, 151, 21))
        self.password_label.setObjectName("password_label")
        self.generate_button = QtWidgets.QPushButton(self.main_widget)
        self.generate_button.setGeometry(QtCore.QRect(190, 120, 171, 32))
        self.generate_button.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.generate_button.setObjectName("generate_button")
        self.add_to_file_button = QtWidgets.QPushButton(self.main_widget)
        self.add_to_file_button.setGeometry(QtCore.QRect(430, 120, 131, 32))
        self.add_to_file_button.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.add_to_file_button.setObjectName("add_to_file_button")
        MainWindow.setCentralWidget(self.main_widget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.website_label.setText(_translate("MainWindow", "Website"))
        self.email_label.setText(_translate("MainWindow", "Email/User Name"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.generate_button.setText(_translate("MainWindow", "Generate Password"))
        self.add_to_file_button.setText(_translate("MainWindow", "Add To File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
