# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(516, 386)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 511, 371))
        self.widget.setObjectName("widget")
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setGeometry(QtCore.QRect(120, 10, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.check_label = QtWidgets.QLabel(self.widget)
        self.check_label.setGeometry(QtCore.QRect(220, 300, 60, 16))
        self.check_label.setObjectName("check_label")
        self.picture_label = QtWidgets.QLabel(self.widget)
        self.picture_label.setGeometry(QtCore.QRect(140, 60, 211, 241))
        self.picture_label.setText("")
        self.picture_label.setPixmap(QtGui.QPixmap("tomato.png"))
        self.picture_label.setObjectName("picture_label")
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setGeometry(QtCore.QRect(20, 180, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.reset_button = QtWidgets.QPushButton(self.widget)
        self.reset_button.setGeometry(QtCore.QRect(360, 180, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.time_label = QtWidgets.QLabel(self.widget)
        self.time_label.setGeometry(QtCore.QRect(190, 170, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_label.setText(_translate("Form", "Pomodoro"))
        self.check_label.setText(_translate("Form", "check"))
        self.start_button.setText(_translate("Form", "Start"))
        self.reset_button.setText(_translate("Form", "Reset"))
        self.time_label.setText(_translate("Form", "00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
