question_data2 = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                   "text": "Nintendo started out as a playing card manufacturer.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                   "text": "A person can get sunburned on a cloudy day.", "answer": "True",
                   "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                   "text": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap Song in 2007.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                   "text": "The cover of The Beatles album &quot;Abbey Road&quot; featured a Volkswagen "
                               "Beetle in the background.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                   "text": "Norwegian producer Kygo released a remix of the song &quot;Sexual i"
                               "Healing&quot; by Marvin Gaye.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                   "text": "The book 1984 was published in 1949.", "answer": "True",
                   "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                   "text": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter "
                               "Blood Heat mode in Half Moon style.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Geography", "type": "boolean", "difficulty": "medium",
                   "text": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "text": "&quot;Half-Life 2&quot; runs on the Source Engine.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Geography", "type": "boolean", "difficulty": "medium",
                   "text": "Vietnam is the only country in the world that starts with V. ",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "text": "Tetris is the #1 best-selling video game of all-time.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Art", "type": "boolean", "difficulty": "medium",
                   "text": "Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                   "text": "The open source program Redis is a relational database server.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "text": "Minecraft can be played with a virtual reality headset.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "History", "type": "boolean", "difficulty": "easy",
                   "text": "The United States of America declared their independence from the British "
                               "Empire on July 4th, 1776.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                   "text": "In most programming languages, the operator ++ is equivalent to the "
                               "statement &quot;+= 1&quot;.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                   "text": "&quot;The Division Bell&quot; is the final album of the progressive rock band "
                               "Pink Floyd.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                   "text": "In the original Star Wars trilogy, David Prowse was the actor who physically "
                               "portrayed Darth Vader.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                   "text": "In Scandinavian languages, the letter &Aring; means river.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "text": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                   "text": "A Saxophone is a brass instrument.", "answer": "False",
                   "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                   "text": "Daft Punk originated in France.", "answer": "True",
                   "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                   "text": "Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
                   "text": "The chemical element Lithium is named after the country of Lithuania.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                   "text": "Sugar contains fat.", "answer": "False",
                   "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                   "text": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                   "difficulty": "hard",
                   "text": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
                   "answer": "True", "incorrect_answers": ["False"]},
                  {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                   "text": "Scotland voted to become an independent country during the referendum "
                               "from September 2014.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                   "difficulty": "medium",
                   "text": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby&#039;s "
                               "All-Star Laff-a-Lympics.",
                   "answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                   "text": "The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
                   "answer": "True", "incorrect_answers": ["False"]}
                  ]
